# Generated by Django 5.0.1 on 2024-02-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household_app', '0002_product_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_rent',
            name='productType',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
