# Generated by Django 5.0.1 on 2024-02-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_app', '0003_product_rent_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='name',
        ),
    ]
