# Generated by Django 5.0.1 on 2024-03-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_app', '0004_remove_rental_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_rent',
            old_name='name',
            new_name='productName',
        ),
    ]
