# Generated by Django 5.0.1 on 2024-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household_app', '0005_rename_name_product_rent_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_rent',
            old_name='productName',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product_rent',
            name='price',
            field=models.FloatField(),
        ),
    ]
