# Generated by Django 5.0.1 on 2024-03-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='prooftype',
        ),
    ]
