# Generated by Django 5.0.1 on 2024-03-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_remove_clientdetails_prooftype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='adharcard',
        ),
        migrations.RemoveField(
            model_name='clientdetails',
            name='bill_no',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='proof',
            field=models.ImageField(default=1, upload_to='pro_image'),
            preserve_default=False,
        ),
    ]
