# Generated by Django 5.0.1 on 2024-03-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_rename_email_contactdetails_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='price',
        ),
    ]
