# Generated by Django 5.0.1 on 2024-03-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_remove_clientdetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='subject',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
