# Generated by Django 5.0.1 on 2024-03-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_confirmorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingproduct',
            name='description',
        ),
    ]
