# Generated by Django 5.0.1 on 2024-03-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_remove_billingproduct_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='confirmorder',
        ),
    ]
