# Generated by Django 5.0.1 on 2024-04-01 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0013_finalorder_billingproduct_final'),
        ('household_app', '0006_rename_productname_product_rent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('subtotal', models.BigIntegerField()),
                ('final', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.finalorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household_app.product_rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
